name: CI
# See https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
  workflow_dispatch:
jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
#          - build: linux
#            os: ubuntu-latest
#            rust: stable
#            target: x86_64-unknown-linux-gnu
#          - build: linux
#            os: ubuntu-24.04-arm
#            rust: stable
#            target: aarch64-unknown-linux-gnu
#          - build: linux
#            os: ubuntu-24.04-arm
#            rust: stable
#            target: armv7-unknown-linux-gnueabi
#          - build: linux
#            os: ubuntu-24.04-arm
#            rust: stable
#            target: arm-unknown-linux-gnueabi
          - build: linux
            os: ubuntu-latest
            rust: nightly
            target: mipsel-unknown-linux-gnu
    steps:

      - uses: actions/checkout@v4
 
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
          qemu: '7.2'
      - run: cargo update -p ring --precise 0.17.14 && cargo install --force bindgen-cli && cargo test --release -Zbuild-std --verbose --target ${{ matrix.target }} --bin privaxy
