name: CI
on:
  workflow_dispatch:

jobs:
  clippy_check:
    name: Run clippy check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rust-src
          targets: wasm32-unknown-unknown 

      - name: Cache Rust
        uses: swatinem/rust-cache@v2

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0

      - name: Install node
        uses: actions/setup-node@v4
        with: 
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'web_frontend/package-lock.json'

      - name: Install node packages
        working-directory: ./web_frontend
        run: npm ci

      - name: Build web frontend
        run: trunk build --release
        working-directory: ./web_frontend

      - name: Run clippy
        # Fail build if there are warnings (standard CI behavior)
        # run: cargo clippy --all-targets -- -D warnings
        # Try to fix and then exit successfully
        run: cargo clippy --fix --all-targets --allow-dirty

  image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: clippy_check 
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: mipsel # Explicitly enable mipsel emulation

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # driver: docker-container
          cleanup: true

      - name: Get image tag
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Auth to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with: 
          context: .
          platforms: linux/amd64,linux/mipsel
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/lichtenshtein/privaxy:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
